import DS from 'ember-data';

export default DS.Model.extend({
  rdwyidtxt: DS.attr('string'),
  lightconddescr: DS.attr('string'),
  injurednmb: DS.attr('number'),
  weatherdescr: DS.attr('string'),
  colldte: DS.attr('date'),
  mannercolldescr: DS.attr('string'),
  surfacetypecde_conddescr: DS.attr('string'),
  roadtypedescr: DS.attr('string'),
  latdecimalnmb: DS.attr('string'),
  longdecimalnmb: DS.attr('string')
}).reopenClass({
    FIXTURES: [
      {
        "id": 1,
       "localitydescr" : "Urban",
       "rumblestripind" : "Y",
       "motorvehinvolvednmb" : "2",
       "rdwyclassdescr" : "Local/City Road",
       "deernmb" : "0",
       "roadtypedescr" : "Multi-Lane Divided 3 or more (Two Way)",
       "deadnmb" : "0",
       "countydescr" : "Marion",
       "hitrunind" : "Y",
       "trailersinvolvednmb" : "0",
       "surfacetypecde_conddescr" : "Dry",
       "mediantypedescr" : "Drivable",
       "internametxt" : "62ND",
       "rdwychardescr" : "Straight/Level",
       "collision_time" : "2:28",
       "constructind" : "N",
       "rdwyjunctiondescr" : "T-Intersection",
       "lightconddescr" : "Daylight",
       "trafficcntrldescr" : "None",
       "schoolzoneind" : "N",
       "colldte" : "2013-12-31T00:00:00",
       "surfacetypedescr" : "ASPHALT",
       "injurednmb" : "0",
       "latdecimalnmb" : "39.866848",
       "rdwyidtxt" : "LAFAYETTE RD",
       "collision_time_am_pm" : "PM",
       "mannercolldescr" : "Same Direction Sideswipe",
       "individual_mr_record" : "902150796",
       "agencyoridescr" : "INDPLS METRO PD",
       "weatherdescr" : "Clear",
       "longdecimalnmb" : "-86.277088",
       "townshipdescr" : "Pike",
       "citydescr" : "Indianapolis",
       "fireind" : "N"
      },
      {
        "id": 2,
       "localitydescr" : "Urban",
       "rumblestripind" : "N",
       "motorvehinvolvednmb" : "2",
       "rdwyclassdescr" : "Local/City Road",
       "deernmb" : "0",
       "roadtypedescr" : "Two Lanes (Two Way)",
       "deadnmb" : "0",
       "countydescr" : "Marion",
       "hitrunind" : "Y",
       "primaryfactordescr" : "OTHER (DRIVER),EXPLAIN IN NARRATIVE",
       "trailersinvolvednmb" : "0",
       "surfacetypecde_conddescr" : "Dry",
       "mediantypedescr" : "None",
       "internametxt" : "W 38TH",
       "rdwychardescr" : "Straight/Grade",
       "collision_time" : "3:45",
       "constructind" : "N",
       "rdwyjunctiondescr" : "Five Point or More",
       "lightconddescr" : "Daylight",
       "trafficcntrldescr" : "Traffic Control Signal",
       "schoolzoneind" : "N",
       "colldte" : "2013-12-31T00:00:00",
       "surfacetypedescr" : "ASPHALT",
       "injurednmb" : "0",
       "latdecimalnmb" : "39.82399978",
       "rdwyidtxt" : "COMMERCIAL DR",
       "collision_time_am_pm" : "PM",
       "mannercolldescr" : "Backing",
       "individual_mr_record" : "902158433",
       "agencyoridescr" : "INDPLS METRO PD",
       "weatherdescr" : "Cloudy",
       "longdecimalnmb" : "-86.2298803",
       "townshipdescr" : "Wayne",
       "citydescr" : "Indianapolis",
       "fireind" : "N"
      }
    ]
});
